dotNet Core Groepsopdracht/Entities/Sponsor.cs
using System;
using System.Collections.Generic;

namespace dotNet_Core_Groepsopdracht.Entities {
	public class Sponsor {

		public Guid Id { get; set; }
		public string Naam { get; set; }
		public string Photo { get; set; }

		public string Postcode { get; set; }

		public string Url { get; set; }

		public List<SponsorEvent> SponsorEvents { get; set; }
	}
}

dotNet Core Groepsopdracht/Models/SponsorViewModel.cs
using System;
using System.Collections.Generic;

namespace dotNet_Core_Groepsopdracht.Models {
	public class SponsorViewModel {
		public Guid Id { get; set; }
		public string Naam { get; set; }
		public string Photo { get; set; }

		public string Postcode { get; set; }

		public string Url { get; set; }

		public List<SponsorEventViewModel> Events { get; set; }
	}
}

dotNet Core Groepsopdracht/Controllers/SponsorController.cs
using dotNet_Core_Groepsopdracht.Attributes;
using dotNet_Core_Groepsopdracht.Data.Database;
using dotNet_Core_Groepsopdracht.Entities;
using dotNet_Core_Groepsopdracht.Models;
using dotNet_Core_Groepsopdracht.Services.Design;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;


namespace dotNet_Core_Groepsopdracht.Controllers {
	[PermissionAuthorize(Permissions.SponsorManagement)]
	public class SponsorController : Controller {

		private readonly IDatabase _database;
		private readonly IPhotoService _photoservice;

		public SponsorController(IDatabase database, IPhotoService photoService) {
			_database = database;
			_photoservice = photoService;
		}
		public IActionResult Index( ) {

			List<SponsorViewModel> viewModel = _database.GetSponsors().Select(x => new SponsorViewModel{
				Naam=x.Naam,
				Photo = x.Photo,
				Id = x.Id,
				Postcode = x.Postcode,
				Url = x.Url
			}).ToList();
			return View(viewModel);
		}
		public IActionResult Detail(Guid id) {
			Sponsor sponsortEntity = _database.FindSponsorById(id);
			if (sponsortEntity == null) {
				return new NotFoundResult( );
			}
			SponsorViewModel sponsorViewModel = new SponsorViewModel{
				Naam = sponsortEntity.Naam,
				Photo = sponsortEntity.Photo,
				Url=sponsortEntity.Url,
				Postcode=sponsortEntity.Postcode,
				Id = sponsortEntity.Id,
				Events = sponsortEntity.SponsorEvents.Select(se => new SponsorEventViewModel {
					Id = se.Event.Id,
					Title = se.Event.Title
				}).ToList()
			};
			return View(sponsorViewModel);
		}


		[HttpGet]
		public IActionResult Create( ) {
			return View( );
		}

		[HttpPost]
		public IActionResult Create(SponsorCreateViewModel viewModel) {

			if (!TryValidateModel(viewModel)) {
				return View(viewModel);
			}
			string imageUrl = null;
			if (viewModel.Image != null) imageUrl = _photoservice.UploadedFile(viewModel.Image);
			Sponsor sponsor = new Sponsor(){
				Id = Guid.NewGuid(),
				Naam = viewModel.Naam,
				Postcode = viewModel.Postcode,
				Url = viewModel.Url,
				Photo = imageUrl,
				SponsorEvents = new List<SponsorEvent>()
			};
			_database.AddSponsor(sponsor);
			return RedirectToAction(nameof(Index));
		}
		[HttpGet]
		public IActionResult Edit(Guid id) {
			var sponsorEntity = _database.FindSponsorById(id);
			if (sponsorEntity == null) {
				return new NotFoundResult( );
			}
			var sponsorViewModel = new SponsorEditViewModel
			{
				Id = sponsorEntity.Id,
				Naam=sponsorEntity.Naam,
				Postcode=sponsorEntity.Postcode,
				Url=sponsorEntity.Url,
				Photo=sponsorEntity.Photo
			};
			return View(sponsorViewModel);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Guid id, SponsorEditViewModel sponsor) {
			if (TryValidateModel(sponsor)) {
				var sponsor1 = _database.FindSponsorById(id);
				if (sponsor1 == null) {
					return new NotFoundResult( );
				}
				sponsor1.Naam = sponsor.Naam;
				sponsor1.Postcode = sponsor.Postcode;
				sponsor1.Url = sponsor.Url;
				if (sponsor.Image != null) {
					string uniqueFileName = _photoservice.UploadedFile(sponsor.Image);
					sponsor1.Photo = uniqueFileName;
				}
				_database.UpdateSponsor(sponsor1, id);
				return RedirectToAction("Index", new { id = id });
			} else {
				return View(sponsor);
			}
		}
		[HttpGet]
		public IActionResult Delete(Guid id) {
			var sponsorEntity = _database.FindSponsorById(id);
			if (sponsorEntity == null) {
				return new NotFoundResult( );
			}
			var svm = new SponsorDeleteViewModel
			{
				Naam = sponsorEntity.Naam,
				Id = sponsorEntity.Id,
			};
			return View(svm);
		}
		[HttpPost]
		public IActionResult Delete(Guid id, SponsorDeleteViewModel sponsor) {
			var sponsorEntity = _database.GetSponsors().SingleOrDefault(sponsor =>sponsor.Id.Equals(id));
			if (sponsorEntity == null) {
				return new NotFoundResult( );
			}
			_database.RemoveSponsor(sponsorEntity);
			return RedirectToAction(nameof(Index));
		}
	}
}

dotNet Core Groepsopdracht/Views/Sponsor/Create.cshtml
@{ViewData["Title"] = "Maak Sponsor aan";}

@model SponsorCreateViewModel


<form asp-controller="Sponsor" asp-action="Create" method="post" enctype="multipart/form-data">

    <div asp-validation-summary="ModelOnly"></div>
    <fieldset>
        <legend>Nieuwe Sponsor:</legend>
        <div class="form-group">
            <label asp-for="Naam"></label>
            <input class="form-control" asp-for="Naam" />
            <span class="text-danger" asp-validation-for="Naam"></span>
        </div>

        <div class="form-group">
            <label asp-for="Postcode"></label>
            <input class="form-control" asp-for="Postcode" />
            <span class="text-danger" asp-validation-for="Postcode"></span>
        </div>
        <div class="form-group">
            <label asp-for="Url"></label>
            <input class="form-control" asp-for="Url" />
            <span class="text-danger" asp-validation-for="Url"></span>
        </div>


        <div class="form-group">
            <label asp-for="Image"></label>
            <input class="form-control" asp-for="Image" />
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
        <button class="btn btn-primary" type="submit">Sponsor aanmaken</button>
        <button class="btn btn-warning" type="reset">Reset</button>
    </fieldset>
</form>

dotNet Core Groepsopdracht/Views/Sponsor/Delete.cshtml
@model SponsorDeleteViewModel

<form asp-controller="Sponsor" asp-action="Delete" method="post">
    <h2> "Ben je zeker dat je de sponsor "@Model.Naam" wilt verwijderen?</h2>
    <button class="btn btn-danger" type="submit"> Sponsor verwijderen </button>
    <a class="btn btn-primary" asp-area="" asp-controller="Sponsor" asp-action="Index">Annuleren</a>
</form>

dotNet Core Groepsopdracht/Views/Sponsor/Detail.cshtml
@model SponsorViewModel

@if (Model != null)
{
    <h2>Sponsor informatie</h2>
    <strong>Sponsor naam</strong>
    <p>@Model.Naam</p>
    <strong>Logo :</strong>
    <img src="@Model.Photo" class="img" />
    <br />
    <strong>Postcode</strong>
    @if (@Model.Postcode == null)
    {
        <p>Deze sponsor heeft geen postcode opgegeven.</p>
    }
    else
    {

        <p>@Model.Postcode</p>
    }

    <strong>Website</strong>
    @if (@Model.Url == null)
    {
        <p>Deze sponsor heeft geen website opgegeven.</p>
    }
    else
    {
        <p>@Model.Url</p>
    }

    //TODO Events aan sponsors linken
    @*<strong> Evenementen </strong>*@
    @*@foreach(var e in Model.Events)
        {
            <a asp-controller="Event" asp-action="Detail" asp-route-id="@e.Id">@e.Title</a>
        }*@
}
else
{
    <p>Deze sponsor bestaat niet!</p>
}

<a class="btn btn-primary" asp-controller="Sponsor" asp-action="Index">Terug naar overview</a>

<style>
    .img {
        height: 100px;
        width: 100px;
        margin: 50px;
    }
</style>

dotNet Core Groepsopdracht/Views/Sponsor/Edit.cshtml
@model SponsorEditViewModel


<h2> Sponsor @Model.Naam aanpassen</h2>

<form asp-controller="Sponsor" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Naam"> Sponsor naam :</label>
        <input asp-for="Naam" class="form-control" />
        <span asp-validation-for="Naam" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"> Logo :</label>
        <img src="@Model.Photo" class="img" />
        <input asp-for="Image" class="form-control" />
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <div class="form-group">
        <label asp-for="Postcode"> Sponsor postcode :</label>
        <input asp-for="Postcode" class="form-control" />
        <span asp-validation-for="Postcode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Url"> Sponsor website :</label>
        <input asp-for="Url" class="form-control" />
        <span asp-validation-for="Url" class="text-danger"></span>
    </div>
    <button class="btn btn-primary" type="submit"> Sponsor wijzigen </button>
    <button class="btn btn-warning" type="reset"> Reset </button>
    <a class="btn btn-primary" asp-controller="Sponsor" asp-action="Index">Annuleren</a>
</form>

<style>
    .img {
        height: 100px;
        width: 100px;
    }
</style>

dotNet Core Groepsopdracht/Views/Sponsor/Index.cshtml
@model IEnumerable<SponsorViewModel>

<h1> Sponsor overzicht </h1>

<a class="text-light btn btn-primary" asp-controller="Sponsor" asp-action="Create">Sponsor aanmaken</a>

@if (Model.Any( ) == false && Model != null) {
    <p> Er zijn geen sponsors</p>
} else {

    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Naam </th>
            <th>Postcode </th>
            <th>Logo </th>
            <th>Website </th>
            <th>Detail </th>
            <th>Edit </th>
            <th>Delete </th>
        </tr>
        @foreach (var sponsor in Model) {
            <tr>
                <td>@sponsor.Naam</td>
                <td>@sponsor.Postcode</td>
                <td><img class="img" src="@sponsor.Photo" /></td>
                <td>@sponsor.Url</td>

                <td>
                    <a asp-controller="Sponsor" asp-action="Detail" asp-route-id="@sponsor.Id">Detail</a>
                </td>
                <td>
                    <a asp-controller="Sponsor" asp-action="Edit" asp-route-id="@sponsor.Id">Edit</a>
                </td>
                <td>
                    <a class="text-danger" asp-controller="Sponsor" asp-action="Delete" asp-route-id="@sponsor.Id">Delete</a>
                </td>

            </tr>
        }
    </table>
}

<style>
    .img {
        height: 100px;
        width: 100px
    }
</style>