dotNet Core Groepsopdracht/Entities/Reservation.cs
using dotNet_Core_Groepsopdracht.Areas.Identity.Data;
using System;

namespace dotNet_Core_Groepsopdracht.Entities {
	public abstract class Reservation {
		public Guid Id { get; set; }
		public Event Event { get; set; }
		public Guid EventId { get; set; }
		public DateTime ReservationDateTime { get; set; }
		public DateTime CreatedDateTime { get; set; }
		public int NumberOfPeople { get; set; }
	}

	public class ReservationLoggedIn : Reservation {
		public Guid UserId { get; set; }
		public User User { get; set; }
	}

	public class ReservationNotLoggedIn : Reservation {
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Email { get; set; }
		public string PhoneNumber { get; set; }
		public string Zipcode { get; set; }
	}
}

dotNet Core Groepsopdracht/Controllers/ReservationController.cs
using dotNet_Core_Groepsopdracht.Areas.Identity.Data;
using dotNet_Core_Groepsopdracht.Data.Database;
using dotNet_Core_Groepsopdracht.Database;
using dotNet_Core_Groepsopdracht.Entities;
using dotNet_Core_Groepsopdracht.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace dotNet_Core_Groepsopdracht.Controllers {

	public class ReservationController : Controller {
		private readonly IDatabase _database;
		private readonly UserManager<User> _userManager;

		public ReservationController(IDatabase database, UserManager<User> userManager) {
			_database = database;
			_userManager = userManager;
		}

		/// <summary>
		/// Displays the reservations of a logged in user
		/// </summary>
		/// <returns></returns>
		[Authorize]
		public IActionResult Index( ) {
			var loggedInReservationsList = new List<ReservationIndexViewModel>();
			var userId = _userManager.GetUserAsync(User).Result.Id;
			var reservationsOfUser = _database.FindReservationsByUserId(userId).OrderBy(r => r.ReservationDateTime);
			foreach (var reservation in reservationsOfUser) {
				loggedInReservationsList.Add(ToListViewModel(reservation));
			}
			return View(loggedInReservationsList);
		}

		public ReservationIndexViewModel ToListViewModel(ReservationLoggedIn reservationLoggedIn) {
			return new ReservationIndexViewModel {
				Id = reservationLoggedIn.Id,
				EventId = reservationLoggedIn.EventId,
				EventTitle = _database.FindEventById(reservationLoggedIn.EventId).Title,
				ReservationDateTime = reservationLoggedIn.ReservationDateTime,
				CreatedDateTime = reservationLoggedIn.CreatedDateTime,
				//UserName = reservationLoggedIn.User.UserName,
				NumberOfPeople = reservationLoggedIn.NumberOfPeople,
				//ReservationDate = reservationLoggedIn.ReservationDateTime.Date.ToShortDateString( ),
				//ReservationTime = reservationLoggedIn.ReservationDateTime.TimeOfDay.ToString( ),
			};
		}

		[HttpGet]
		public IActionResult Create(Guid id) {
			var _event = _database.FindEventById(id);
			if (_event == null) return new NotFoundResult( );

			// Dropdown list for possible dates
			//List<string[]> periods = new List<string[]>();
			List<string> periods = new List<string>();
			List<SelectListItem> possibleDates = new List<SelectListItem>();
			// TODO: Dropdown list is now displaying all dates, but not the hours yet!
			foreach (var period in _database.FindPeriodsByEventId(id)) {
				//for (var date = period.Start.Date; date <= period.End.Date; date = date.AddDays(1.0)) {
				string txt = period.Start.ToShortDateString() + " " + period.Start.ToString("HH:mm");
				if (period.Start != period.End) txt = txt + "-" + period.End.ToString("HH:mm");
				var newItem = new SelectListItem {Value = period.Start.Date.ToString(), Text = txt};
				possibleDates.Add(newItem);
				//}
				string periodDay = period.Start.Date.ToString();
				string periodStartH = period.Start.ToString("HH");
				//string periodStartH2 = period.Start.Hour.ToString();
				string periodStartM = period.Start.ToString("mm");
				string periodEndH = period.End.ToString("HH");
				string periodEndM = period.End.ToString("mm");
				periods.Add($"[ '{periodDay}', {periodStartH}, {periodStartM}, {periodEndH}, {periodEndM}, {period.Start.Year}, {period.Start.Month}, {period.Start.Day}]");

			}

			var createLoggedInReservationViewModel = new ReservationCreateLoggedInViewModel()
				{
				EventId = _event.Id,
				EventTitle = _event.Title,
				PossibleDates = possibleDates,
				Periods = periods
			};

			var createNotLoggedInReservationViewModel = new ReservationCreateNotLoggedInViewModel()
				{
				EventId = _event.Id,
				EventTitle = _event.Title,
				PossibleDates = possibleDates,
				Periods = periods
			};

			if (!User.Identity.IsAuthenticated) return View("CreateNotLoggedInReservation", createNotLoggedInReservationViewModel);

			var loggedInUser = _userManager.GetUserAsync(User).Result;
			var user = $"{loggedInUser.FirstName} {loggedInUser.LastName}"; // TODO: For now, only shows part of the emailadres
			createLoggedInReservationViewModel.UserName = user;
			return View("CreateLoggedInReservation", createLoggedInReservationViewModel);
		}

		[HttpPost]
		public IActionResult CreateLoggedIn([FromForm] ReservationCreateLoggedInViewModel reservationViewModel) {
			if (!TryValidateModel(reservationViewModel)) {
				List<string> periods = new List<string>();
				List<SelectListItem> possibleDates = new List<SelectListItem>();
				foreach (var period in _database.FindPeriodsByEventId(reservationViewModel.EventId)) {
					string txt = period.Start.ToShortDateString() + " " + period.Start.ToString("HH:mm");
					if (period.Start != period.End) txt = txt + "-" + period.End.ToString("HH:mm");
					var newItem = new SelectListItem {Value = period.Start.Date.ToString(), Text = txt};
					possibleDates.Add(newItem);
					string periodDay = period.Start.Date.ToString();
					string periodStartH = period.Start.ToString("HH");
					string periodStartM = period.Start.ToString("mm");
					string periodEndH = period.End.ToString("HH");
					string periodEndM = period.End.ToString("mm");
					periods.Add("[ '" + periodDay + "', " + periodStartH + ", " + periodStartM + ", " + periodEndH + ", " + periodEndM + ", " +
						period.Start.ToString("yyyy") + ", " + period.Start.ToString("MM") + ", " + period.Start.ToString("dd") + " ]");
				}
				reservationViewModel.Periods = periods;
				reservationViewModel.PossibleDates = possibleDates;
				return View("CreateLoggedInReservation", reservationViewModel);
			}
			DateTime reservationDateTime = DateTime.Parse(reservationViewModel.ReservationTime, null, System.Globalization.DateTimeStyles.RoundtripKind);
			reservationDateTime = reservationDateTime.AddHours(1); // Add hour becouse time is passed in UTC and we are +1
			var loggedInReservation = new ReservationLoggedIn() {
				Id = Guid.NewGuid(),
				User = _userManager.GetUserAsync(User).Result,
				ReservationDateTime = reservationDateTime,
				CreatedDateTime = DateTime.Now,
				Event = _database.FindEventById(reservationViewModel.EventId),
				NumberOfPeople = reservationViewModel.NumberOfPeople,
			};

			_database.AddReservationLoggedIn(loggedInReservation);

			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult CreateNotLoggedIn([FromForm] ReservationCreateNotLoggedInViewModel reservationViewModel) {
			if (!TryValidateModel(reservationViewModel)) {
				List<string> periods = new List<string>();
				List<SelectListItem> possibleDates = new List<SelectListItem>();
				foreach (var period in _database.FindPeriodsByEventId(reservationViewModel.EventId)) {
					string txt = period.Start.ToShortDateString() + " " + period.Start.ToString("HH:mm");
					if (period.Start != period.End) txt = txt + "-" + period.End.ToString("HH:mm");
					var newItem = new SelectListItem {Value = period.Start.Date.ToString(), Text = txt};
					possibleDates.Add(newItem);
					string periodDay = period.Start.Date.ToString();
					string periodStartH = period.Start.ToString("HH");
					string periodStartM = period.Start.ToString("mm");
					string periodEndH = period.End.ToString("HH");
					string periodEndM = period.End.ToString("mm");
					periods.Add("[ '" + periodDay + "', " + periodStartH + ", " + periodStartM + ", " + periodEndH + ", " + periodEndM + ", " +
						period.Start.ToString("yyyy") + ", " + period.Start.ToString("MM") + ", " + period.Start.ToString("dd") + " ]");
				}
				reservationViewModel.Periods = periods;
				reservationViewModel.PossibleDates = possibleDates;
				return View("CreateNotLoggedInReservation", reservationViewModel);
			}
			DateTime reservationDateTime = DateTime.Parse(reservationViewModel.ReservationTime, null, System.Globalization.DateTimeStyles.RoundtripKind);
			reservationDateTime = reservationDateTime.AddHours(1); // Add hour becouse time is passed in UTC and we are +1
			var notLoggedInReservation = new ReservationNotLoggedIn() {
				Id = Guid.NewGuid(),
				ReservationDateTime = reservationDateTime,
				CreatedDateTime = DateTime.Now,
				Event = _database.FindEventById(reservationViewModel.EventId),
				NumberOfPeople = reservationViewModel.NumberOfPeople,
				FirstName = reservationViewModel.FirstName,
				LastName = reservationViewModel.LastName,
				Email = reservationViewModel.Email,
				PhoneNumber = reservationViewModel.PhoneNumber,
				Zipcode = reservationViewModel.Zipcode,
			};

			// TODO: Fix DB: It gets stuck on SaveChanges() => Duplicate entry exception for primary key
			// Eindigt op login pagina ... ??
			// User is missing in DB!!
			_database.AddReservationNotLoggedIn(notLoggedInReservation);

			return RedirectToAction("ConfirmNotLoggedIn", new { id = notLoggedInReservation.Id });
		}

		/// <summary>
		/// Displays the reservation that a not-logged-in user just made
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		[HttpGet]
		public IActionResult ConfirmNotLoggedIn(Guid id) {
			var notLoggedInReservation = _database.FindReservationNotLoggedInById(id);
			if (notLoggedInReservation == null) return new NotFoundResult( );
			string reservationDate = notLoggedInReservation.ReservationDateTime.ToString("f", CultureInfo.CreateSpecificCulture("nl-BE"));
			var reservationViewModel = new ReservationCreateNotLoggedInViewModel {
				//TODO: Add ReservationDateTime property
				//ReservationDate = notLoggedInReservation.ReservationDateTime.ToString(),

				FirstName = notLoggedInReservation.FirstName,
				LastName = notLoggedInReservation.LastName,
				Email = notLoggedInReservation.Email,
				ReservationDate = reservationDate,
				NumberOfPeople = notLoggedInReservation.NumberOfPeople,
				EventId = notLoggedInReservation.EventId,
				//Event = _database.FindEventById(EventId),

dotNet Core Groepsopdracht/Views/Reservation/ConfirmNotLoggedIn.cshtml
@model ReservationCreateNotLoggedInViewModel
@{ ViewData["Title"] = "Reservatie voltooid";}

<h1>Succes!</h1>
@Html.Hidden("EventId")
<h2>Reservatie voor @Model.EventTitle</h2>

<div>
    <p>Op naam van @Model.FirstName @Model.LastName</p>
    @*TODO: gekozen datum en tijdstip invoeren*@
    <p>Op @Model.ReservationDate</p>
    <p>Voor @Model.NumberOfPeople personen</p>
</div>

@*TODO: Why is fake button not working? I wanted a fake button in the same style as in the event overview, but it's not working ... Why, Oh why?*@
@*<div class="container" style="margin: 20px 0 20px 0">
        <p class="fakeButton "> <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Terug naar Evenementen</a></p>
    </div>*@

<a class="btn btn-primary" asp-area="" asp-controller="Event" asp-action="Index">Terug naar Evenementen</a>

dotNet Core Groepsopdracht/Views/Reservation/CreateLoggedInReservation.cshtml
@model ReservationCreateLoggedInViewModel


<h2 class="mt-4 mb-3">@Model.EventTitle</h2>
<h3 class="mt-4 mb-3">Reservatie op naam van: @Model.UserName</h3>

<script type="text/javascript" src="/js/reservations.js"></script>
<script>
var periods = new Array();
@foreach(string period in @Model.Periods)
{
    <text> periods.push(@Html.Raw(period)); </text>
}

</script>

<form name="form1" asp-controller="Reservation" asp-action="CreateLoggedIn" enctype="multipart/form-data" method="post">
    @*<input value="@Model.EventId" asp-for="EventId" />*@
    @Html.Hidden("EventId")
    @Html.Hidden("Periods")
    <div class="form-group">
        <label asp-for="ReservationDate"></label>
        <select asp-for="ReservationDate" asp-items="Model.PossibleDates" onchange="showTimes(this.value);" id="dateSelector">
            <option disabled selected value="None"> -- Datum -- </option>
        </select>
        @*<span class="text-danger" asp-validation-for="ReservationDate"></span>*@
    </div>

    <div class="form-group" id="timeSelectorDiv" style="display:none">
        <label asp-for="ReservationTime"></label>
        <select asp-for="ReservationTime" id="timeSelector">
            @*<option disabled selected value="None"> -- Tijd -- </option>*@
        </select>
    </div>


    <div class="form-group">
        <label asp-for="NumberOfPeople"></label>
        <input class="form-control" asp-for="NumberOfPeople" />
        <span class="text-danger" asp-validation-for="NumberOfPeople"></span>
    </div>
    <button class="btn btn-primary" type="submit">Maak Reservatie</button>
</form>

dotNet Core Groepsopdracht/Views/Reservation/CreateNotLoggedInReservation.cshtml
@model ReservationCreateNotLoggedInViewModel

<h2 class="mt-4 mb-3">@Model.EventTitle</h2>
<h4 class="mt-4 mb-3">Geef de nodige info</h4>

<script type="text/javascript" src="/js/reservations.js"></script>
<script>
var periods = new Array();
@foreach(string period in @Model.Periods)
{
    <text> periods.push(@Html.Raw(period)); </text>
}

</script>

<form asp-controller="Reservation" asp-action="CreateNotLoggedIn" method="post">
    @Html.Hidden("EventId")
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input class="form-control" asp-for="FirstName" />
        <span class="text-danger" asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
        <span class="text-danger" asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input class="form-control" asp-for="PhoneNumber" />
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
    </div>
    <div class="form-group">
        <label asp-for="Zipcode"></label>
        <input class="form-control" asp-for="Zipcode" />
        <span class="text-danger" asp-validation-for="Zipcode"></span>
    </div>

    <div class="form-group">
        <label asp-for="ReservationDate"></label>
        <select asp-for="ReservationDate" asp-items="Model.PossibleDates" onchange="showTimes(this.value);" id="dateSelector">
            <option disabled selected value="None"> -- Datum -- </option>
        </select>
    </div>

    <div class="form-group" id="timeSelectorDiv" style="display:none">
        <label asp-for="ReservationTime"></label>
        <select asp-for="ReservationTime" id="timeSelector"></select>
    </div>

    <div class="form-group">
        <label asp-for="NumberOfPeople"></label>
        <input class="form-control" asp-for="NumberOfPeople" />
        <span class="text-danger" asp-validation-for="NumberOfPeople"></span>
    </div>

    <button class="btn btn-primary" type="submit">Maak Reservatie</button>
</form>

dotNet Core Groepsopdracht/Views/Reservation/Delete.cshtml
@model ReservationDeleteViewModel

@if (Model.NumberOfPeople == 1)
{
    <p>Bent u zeker dat u de reservatie voor @Model.NumberOfPeople persoon voor @Model.EventTitle op naam van @Model.Firstname @Model.Lastname wilt verwijderen?</p>
}

else
{
<p>Bent u zeker dat u de reservatie voor @Model.NumberOfPeople personen voor @Model.EventTitle op naam van @Model.Firstname @Model.Lastname wilt verwijderen?</p>
}

<form asp-action="ConfirmDelete" asp-controller="Reservation" method="post" asp-route-id="@Model.Id">
    <button class="btn btn-danger" type="submit">Verwijder</button>
    <a class="btn btn-primary" asp-controller="Reservation" asp-action="Index" asp-route-id="@Model.Id">Annuleer</a>
</form>

dotNet Core Groepsopdracht/Views/Reservation/EditLoggedInReservation.cshtml
@model ReservationCreateLoggedInViewModel
@* TODO: Moet hiervoor geen aparte viewmodel gemaakt worden? -> dit is niet mijn ticket*@

<form asp-controller="Reservation" asp-action="Edit" method="post">

    <div class="form-group text-white">
        <label asp-for="ReservationDate"></label>
        <select asp-for="ReservationDate" asp-items="Model.PossibleDates" onchange="ChangeTimes();" id="dateSelector"></select>
        <span class="text-danger" asp-validation-for="ReservationDate"></span>
    </div>

    <div class="form-group text-white">
        <label asp-for="ReservationTime"></label>
        <select asp-for="ReservationTime" id="timeSelector"></select>
        <span class="text-danger" asp-validation-for="ReservationTime"></span>
    </div>

    <div class="form-group text-white">
        <label asp-for="NumberOfPeople"></label>
        <input class="form-control" asp-for="NumberOfPeople" />
        <span class="text-danger" asp-validation-for="NumberOfPeople"></span>
    </div>

    <button class="btn btn-primary" type="submit">Reservatie aanpassen.</button>
</form>

<script>
    function ChangeTimes() {
        //console.log("ChangeTimes function executing");

        var dateSelector = document.getElementById("dateSelector");
        var dateString = dateSelector.options[dateSelector.selectedIndex].value;
        //console.log(dateString);

        var timeSelector = document.getElementById("timeSelector");

        //grab the possibletimes from the model:
        var modelRaw = '@Html.Raw(Json.Serialize(Model))';
        var parseModel = JSON.parse(modelRaw);
        var possibleTimes = parseModel.PossibleTimes[dateSelector.selectedIndex];
        //console.log(possibleTimes);
        for (var i = 0; i < possibleTimes.length; i++) {

            var tag = document.createElement("option");
            var text = document.createTextNode(possibleTimes[i]);
            tag.appendChild(text);
            timeSelector.appendChild(tag);
        }

    }
</script>

dotNet Core Groepsopdracht/Views/Reservation/EventList.cshtml
@model ReservationEventListViewModel


<h1> Event Lijst Reservaties: </h1>


    <img src="@Model.Image"/>
    
    <p>Evenement adres: @Model.Address</p>
    
    
    <a asp-action="Detail" asp-controller="Event" asp-route-id="@Model.EventId">@Model.EventTitle</a>

    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Naam</th>
            <th>Aantal mensen</th>
            <th>Reservatie-datum</th>
        </tr>
     @if (Model.Reservations != null && Model.Reservations.Count > 0)
        {
   
        @foreach (var reservatie in Model.Reservations)
        {
            <tr>
                <td>@reservatie.Name</td>
                <td>@reservatie.NumberOfPeople</td>
                <td>@reservatie.ReservationDateTime</td>
                
            </tr>
        }
    }
    else
    {
            <p>Momenteel zijn er geen reservaties</p>
        
    }
</table>

dotNet Core Groepsopdracht/Views/Reservation/Index.cshtml
@model IEnumerable<ReservationIndexViewModel>

    <div class="mb-4">
        <a class="btn btn-primary" asp-area="" asp-controller="Event" asp-action="Index">Terug naar evenementen</a>
        </div>
        
        @if (Model != null && Model.Any())
        {
            <h1 class="mb-5">Overzicht gemaakte reservaties</h1>
            @foreach (var reservation in Model)
            {
                <hr />
                <div class="mb-4">
                    @*TODO: link doesn't work, there is no Event - Detail yet
                        TODO: Fix indent of links*@
                    <h2><a class="nav-link text-primary pl-0" asp-controller="Event" asp-action="Detail" asp-route-id="@reservation.EventId">@reservation.EventTitle</a></h2>
                    <h4>  Reservatie op datum van @reservation.ReservationDateTime.ToString("dd/MM/yyyy HH:mm")</h4>
                    <h4>  Aantal personen: @reservation.NumberOfPeople</h4>
                    @*TODO: link doesn't work, there is no Reservation - Detail yet*@
                    @*<a class="nav-link text-primary pl-0" asp-controller="Reservation" asp-action="Detail" asp-route-id="@reservation.Id">Detail</a>*@
                    <a class="nav-link text-danger pl-0" asp-controller="Reservation" asp-action="Delete" asp-route-id="@reservation.Id">Delete</a>
                </div>
            }
            <hr />
        }

        else
        {
            <h1> U heeft geen reservaties</h1>
        }

dotNet Core Groepsopdracht/Views/Reservation/List.cshtml
@model UserReservationListViewModel


<h1> Lijst Reservaties </h1>

<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Event naam</th>
        <th>Beschrijving</th>
        <th>Afbeelding</th>
        <th>Adres</th>
        <th>Aantal mensen</th>
        <th>Datum</th>

    </tr>
    @if (Model.Reservations.Any()&& Model.Reservations!=null)
    {
        @foreach (var reservatie in Model.Reservations)
        {
<tr>
    <td>@reservatie.Event.Title</td>
    <td>@reservatie.Event.Description</td>
    <td>@reservatie.Event.Image</td>
    <td>@reservatie.Event.Address</td>
    <td>@reservatie.NumberOfPeople</td>
    <td>@reservatie.ReservationDateTime</td>

</tr>
        }
    }
    else
    {
        <td>
            <p>Deze klant heeft momenteel geen reservaties</p>
        </td>

    }
</table>