dotNet Core Groepsopdracht/Entities/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace dotNet_Core_Groepsopdracht.Entities {
	public class Event {

		public Guid Id { get; set; }
		public String Title { get; set; }
		public int MaxCap { get; set; }
		public int MinCap { get; set; }
		public Address Address { get; set; }
		public List<Period> Periods { get; set; }
		public string Description { get; set; }
		public string Image { get; set; }
		public string Price { get; set; }
		public List<SponsorEvent> SponsorEvents { get; set; }

		public List<ReservationLoggedIn> ReservationsLoggedIn { get; set; }
		public List<ReservationNotLoggedIn> ReservationsNotLoggedIn { get; set; }

		public int MaxPlacesLeft( ) {
			int max = 0;
			foreach (Period period in Periods) {
				int currentPlacesLeft = MaxCap;
				if (ReservationsLoggedIn != null)
					foreach (ReservationLoggedIn reservation in ReservationsLoggedIn.Where(r => r.ReservationDateTime <= period.End && r.ReservationDateTime >= period.Start)) {
						currentPlacesLeft -= reservation.NumberOfPeople;
					}
				if (ReservationsNotLoggedIn != null)
					foreach (ReservationNotLoggedIn reservation in ReservationsNotLoggedIn.Where(r => r.ReservationDateTime <= period.End && r.ReservationDateTime >= period.Start)) {
						currentPlacesLeft -= reservation.NumberOfPeople;
					}
				if (currentPlacesLeft > max) { max = currentPlacesLeft; }
			}
			return max;
		}
	}
}

dotNet Core Groepsopdracht/Controllers/EventController.cs
using dotNet_Core_Groepsopdracht.Attributes;
using dotNet_Core_Groepsopdracht.Data.Database;
using dotNet_Core_Groepsopdracht.Entities;
using dotNet_Core_Groepsopdracht.Models;
using dotNet_Core_Groepsopdracht.Services.Design;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Security.Permissions;


namespace dotNet_Core_Groepsopdracht.Controllers {

	public class EventController : Controller {
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IDatabase _database;
		private readonly IPhotoService _photoService;
		//private static readonly List<PeriodViewModel> nieuweLijst = new List<PeriodViewModel>();

		public EventController(IWebHostEnvironment webhostEnvironment, IDatabase database, IPhotoService photoService) {
			_webHostEnvironment = webhostEnvironment;
			_database = database;
			_photoService = photoService;
		}

		//[HttpGet]
		public IActionResult Index( ) {
			List<OverviewEventViewModel> lijst = new List<OverviewEventViewModel>();

			foreach (Event eventEntity in _database.GetEvents( )
												   .GroupBy(e => e.Periods[^1].End < DateTime.Now)
												   .OrderBy(x => x.Key)
												   .SelectMany(x => x.Key ?
														x.OrderByDescending(e => e.Periods[^1].End) :
														x.OrderBy(e => e.Periods[0].Start))) {
				lijst.Add(new OverviewEventViewModel {
					Id = eventEntity.Id,
					Title = eventEntity.Title,
					Address = eventEntity.Address is null ? new AddressViewModel( ) :
						new AddressViewModel {
							Id = eventEntity.Address.Id,
							Street = eventEntity.Address.Street,
							Number = eventEntity.Address.Number,
							Bus = eventEntity.Address.Bus,
							ZipCode = eventEntity.Address.ZipCode,
							City = eventEntity.Address.City
						},
					PeriodeEvenement = new DateTime[0], // TODO: add this
					Description = eventEntity.Description,
					Image = eventEntity.Image,
					Price = eventEntity.Price,
					Sponsors = new List<SponsorViewModel>( ), // TODO: add sponsors
					MaxPlacesLeft = eventEntity.MaxPlacesLeft( )
				});
			}

			return View(lijst);
		}

		//[HttpGet]
		//public IActionResult Detail( ) {
		//	return View( );
		//}

		[HttpGet]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult Create( ) {
			EventCreateViewModel ecvm = new EventCreateViewModel();
			ecvm.Number = 1;//zet de input al op min 1 want de value in input (Create.cshtml) werkt natuurlijk niet
			ecvm.PeriodLijst.Add(new PeriodViewModel( ) { Id = Guid.NewGuid( ), RemoveRemoveButton = true });
			return View(ecvm);
		}

		[HttpPost]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult Create([FromForm] EventCreateViewModel ecvm) {
			if (TryValidateModel(ecvm)) {
				List<Period> periods = new List<Period>();

				Address newAdress = new Address{
					Street = ecvm.Street,
					Number = ecvm.Number,
					Bus = ecvm.Bus,
					City = ecvm.City,
					ZipCode = ecvm.ZipCode,
					Id = Guid.NewGuid()
				};
				Event newEvent = new Event{
					Id = Guid.NewGuid(),
					Title = ecvm.Title,
					MaxCap = ecvm.MaxCap,
					MinCap = ecvm.MinCap,
					Description = ecvm.Description,
					Address = newAdress,
					Image = _photoService.UploadedFile(ecvm.Image),
					Price = ecvm.Price
				};


				foreach (PeriodViewModel pvm in ecvm.PeriodLijst) {
					if (pvm == null) {
						ModelState.AddModelError("Periode", "Je moet de periode invullen");
						return View(ecvm);
					}
					if (!ecvm.PeriodIsCorrect(pvm)) {
						ModelState.AddModelError("Periode", "Startdatum periode kan niet later zijn dan de einddatum van dezelfde periode");
						return View(ecvm);
					}

					//checkt period for correct start en end
					Period newPeriod = new Period
				{
						Start = pvm.Start,
						End = pvm.End,
						//Id = Guid.NewGuid(), // TO CHECK: All PeriodID's in the DB are the same for now!! Is that the intention?
						Event = newEvent
					};
					periods.Add(newPeriod);
				}
				newEvent.Periods = periods;
				//add event to db:
				_database.AddEvent(newEvent);
				return RedirectToAction("Index");
			} else {
				return View(ecvm);
			}
		}

		[HttpGet]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult Edit(Guid id) {
			Event eventToEdit = _database.FindEventById(id);
			if (eventToEdit == null) return new NotFoundResult( );

			List<SelectListItem> sponsortags = new List<SelectListItem>();
			foreach (Sponsor sponsor in _database.GetSponsors( )) {
				sponsortags.Add(new SelectListItem { Value = sponsor.Naam, Text = sponsor.Naam });
			}

			EventEditViewModel eventEditViewModel = new EventEditViewModel()
			{
				Id = eventToEdit.Id,
				Title = eventToEdit.Title,
				MaxCap = eventToEdit.MaxCap,
				MinCap = eventToEdit.MinCap,
				Street = eventToEdit.Address is null ? null : eventToEdit.Address.Street,
				Number = eventToEdit.Address is null ? 0 : eventToEdit.Address.Number,
				Bus = eventToEdit.Address is null ? null : eventToEdit.Address.Bus,
				ZipCode = eventToEdit.Address is null ? null : eventToEdit.Address.ZipCode,
				City = eventToEdit.Address is null ? null : eventToEdit.Address.City,
				CurrentImgPath=eventToEdit.Image,
				Description = eventToEdit.Description,
				PeriodLijst=new List<PeriodViewModel>(),
				Price = eventToEdit.Price,
				SelectedSponsors= eventToEdit.SponsorEvents is null ? null : eventToEdit.SponsorEvents.Select(x=> x.Sponsor.Naam).ToArray()
			};
			foreach (Period period in eventToEdit.Periods) {
				PeriodViewModel pvm = new PeriodViewModel{
					Id = period.Id,
					Start = period.Start,
					End = period.End
				};
				eventEditViewModel.PeriodLijst.Add(pvm);
			}
			eventEditViewModel.Sponsortags = sponsortags;
			return View(eventEditViewModel);
		}
		[HttpPost]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult Edit(Guid id, [FromForm] EventEditViewModel eevm) {

			if (TryValidateModel(eevm)) {
				List<SelectListItem> sponsortags = new List<SelectListItem>();

				foreach (Sponsor sponsor in _database.GetSponsors( )) {
					sponsortags.Add(new SelectListItem { Value = sponsor.Naam, Text = sponsor.Naam });
				}

				//convert viewmodel to event entity:
				Address newAdress = new Address{
					Street = eevm.Street,
					Number = eevm.Number,
					Bus = eevm.Bus,
					City = eevm.City,
					ZipCode = eevm.ZipCode
				};
				Event newEvent = _database.FindEventById(id);
				//newEvent.Id = eevm.Id;
				newEvent.Title = eevm.Title;
				newEvent.MaxCap = eevm.MaxCap;
				newEvent.MinCap = eevm.MinCap;
				newEvent.Description = eevm.Description;
				newEvent.Address = newAdress;
				newEvent.Price = eevm.Price;
				newEvent.Periods = new List<Period>( );
				newEvent.SponsorEvents = new List<SponsorEvent>( );

				if (eevm.Image != null) {
					string uniquefileName = _photoService.UploadedFile(eevm.Image);
					newEvent.Image = uniquefileName;
				}
				if (eevm.PeriodLijst == null) {
					eevm.PeriodLijst = new List<PeriodViewModel>( );
				}
				foreach (PeriodViewModel pvm in eevm.PeriodLijst) {
					if (pvm != null) {
						if (eevm.PeriodIsCorrect(pvm)) {//checkt period for correct start en end
							Period newPeriod = new Period{
								Start = pvm.Start,
								End = pvm.End,
								Event = newEvent
							};
							newEvent.Periods.Add(newPeriod);
						} else {
							ModelState.AddModelError("Periode", "Startdatum periode kan niet later zijn dan de einddatum van dezelfde periode.");
							return View(eevm);
						}
					} else {
						ModelState.AddModelError("Periode", "Je moet de periode invullen.");
						return View(eevm);
					}
				}
				IEnumerable<Sponsor> sponsorList= _database.GetSponsors();

				IEnumerable<Sponsor> selectedSponsors = eevm.SelectedSponsors is null? new List<Sponsor>() : sponsorList.Where(s => eevm.SelectedSponsors.Contains(s.Naam));
				foreach (Sponsor sponsor in selectedSponsors) {
					newEvent.SponsorEvents.Add(new SponsorEvent {
						Event = newEvent,
						EventId = newEvent.Id,
						Sponsor = sponsor,
						SponsorId = sponsor.Id,
					});
				}
				eevm.Sponsortags = sponsortags;
				//update database:
				_database.UpdateEvent(newEvent, newEvent.Id);

				return RedirectToAction("Index");
			} else { return View(eevm); }
		}
		[HttpGet]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult Delete(Guid id) {
			Event eventToDelete = _database.FindEventById(id);
			if (eventToDelete == null) return new NotFoundResult( );

			EventDeleteViewModel eventDeleteViewModel = new EventDeleteViewModel()
				{
				Title = eventToDelete.Title,
				Id=eventToDelete.Id

			};
			return View(eventDeleteViewModel);
		}

		[HttpPost]
		[PermissionAuthorize(Permissions.EventManagement)]
		public IActionResult ConfirmDelete(Guid id) {
			Event eventToDelete = _database.FindEventById(id);
			if (eventToDelete == null) return new NotFoundResult( );

			_database.RemoveEvent(eventToDelete);

			//if (!_database.FindEventById(id)) return new NotFoundResult( );//dit stuk snap ik niet

			return RedirectToAction("Index");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddPeriodViewModelToEvent([Bind("PeriodLijst")] EventCreateViewModel ecvm) {
			ecvm.PeriodLijst.Add(new PeriodViewModel { Id = Guid.NewGuid( ) });
			return PartialView("PeriodeViewModel", ecvm);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddPeriodViewModelToEditEvent([Bind("PeriodLijst")] EventEditViewModel eevm) {
			if (eevm.PeriodLijst == null) { eevm.PeriodLijst = new List<PeriodViewModel>( ); }
			eevm.PeriodLijst.Add(new PeriodViewModel { Id = Guid.NewGuid( ) });
			return PartialView("PeriodEditViewModel", eevm);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]

dotNet Core Groepsopdracht/Views/Event/Create.cshtml
@model EventCreateViewModel
@{
    ViewData["Title"] = "Create Evenement";
}

<style>
    input[type=datetime] {
        width: 200px;
        margin-right: 15px;
    }
</style>

<h1>Evenement aanmaken</h1>
<p class="mt-5" style="font-size:small">* Velden met een asterisk moeten ingevuld worden</p>

<form id="form" asp-controller="Event" asp-action="Create" method="post" enctype="multipart/form-data">

    <div asp-validation-summary="ModelOnly"></div>
    <fieldset class="mt-3 mb-5">
        <legend class="mb-5">Info Evenement:</legend>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title" />
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>

        <div class="form-group">
            <label asp-for="MaxCap"></label>
            <input class="form-control" asp-for="MaxCap" />
            <span class="text-danger" asp-validation-for="MaxCap"></span>
        </div>
        <div class="form-group">
            <label asp-for="MinCap"></label>
            <input class="form-control" asp-for="MinCap" />
            <span class="text-danger" asp-validation-for="MinCap"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea class="form-control" id="Description" asp-for="Description"></textarea>
            <span class="text-danger" asp-validation-for="Description"></span>
            <span id="DescriptionChars" asp-validation-for="Description"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <input class="form-control" asp-for="Price" />
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>

        <div class="form-group">
            <label asp-for="Image"></label>
            <input class="form-control" asp-for="Image" />
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
    </fieldset>

    @*Adress gedeelte*@
    <fieldset class="mt-3 mb-4">
        <legend class="mb-5">Adres:</legend>
        <div class="form-group">
            <label asp-for="Street"></label>
            <input class="form-control" asp-for="Street" />
            <span class="text-danger" asp-validation-for="Street"></span>
        </div>
        <div class="form-group">
            <label asp-for="Number"></label>
            <input class="form-control" asp-for="Number" />
            <span class="text-danger" asp-validation-for="Number"></span>
        </div>
        <div class="form-group">
            <label asp-for="Bus"></label>
            <input class="form-control" asp-for="Bus" />
            <span class="text-danger" asp-validation-for="Bus"></span>
        </div>
        <div class="form-group">
            <label asp-for="City"></label>
            <input class="form-control" asp-for="City" />
            <span class="text-danger" asp-validation-for="City"></span>
        </div>
        <div class="form-group">
            <label asp-for="ZipCode"></label>
            <input class="form-control" asp-for="ZipCode" />
            <span class="text-danger" asp-validation-for="ZipCode"></span>
        </div>
    </fieldset>
    @*****************************************@
    <fieldset>
        <legend>Periode Evenement:</legend>


        <div id="PeriodViewModelContainer">
            @*when "verwijder datum" gaat hij de eerste datum verwijderen*@
            @Html.EditorFor(model => model.PeriodLijst)
        </div>
        <div class="row">
            @*<div class="col-md-4">
                    <input class="btn btn-primary" type="button" id="btnAddPeriod" value="Voeg een nieuwe datum toe" />
                </div>*@
            <div class="row">
                <div class="col-md-4">
                    <input class="btn btn-primary" type="button" onclick="AddPeriodeVM()" id="btnAddPeriod" value="Voeg een nieuwe datum toe" />
                </div>
            </div>
            <br />@Html.ValidationSummary(false, "", new { @class = "text-danger" })

        </div>
    </fieldset><br /><br /><br />
    <button class="btn btn-primary" type="submit">Aanmaken</button>
    <button class="btn btn-warning text-dark" type="reset">Reset</button>
</form>
<br />
<form asp-action="Index" method="get">
    <button class="btn btn-primary" type="submit">Terug</button>
</form>




@section Scripts
{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    @*
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    *@

    <script src="~/js/PartialViewAdder.js"></script>
    <script type="text/javascript">
        $(".datepicker").datetimepicker({
            format: 'DD/MM/YYYY HH:mm'
        });
        AddPeriodItemListener("btnAddPeriod", "/Event/AddPeriodViewModelToEvent", "PeriodViewModelContainer");

        function RemovePeriodVM(id) {
            $.ajax({
                async: true,
                data: $('#form').serialize(),
                type: "POST",
                url: `/Event/RemovePeriodViewModelFromEvent/${id}`,
                success: function (str) {
                    document.querySelector(`[modelId="${id}"]`).remove();
                }
            });
        }
        document.getElementById("Description").addEventListener('input', upDateDescriptionChars);
        function upDateDescriptionChars() {
            let currentChars = String(500 - this.value.length);
            document.getElementById("DescriptionChars").innerHTML = currentChars + "/500 beschikbaar."

        }

        let desChars = String(500 - document.getElementById("Description").value.length);
        document.getElementById("DescriptionChars").innerHTML = desChars + "/500 beschikbaar."


    </script>

}

dotNet Core Groepsopdracht/Views/Event/Delete.cshtml
@model EventDeleteViewModel

    @*// NOTE: action is called "ConfirmDelete"*@
    <form asp-controller="Event" asp-action="ConfirmDelete" asp-route-id="@Model.Id" method="post">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>
        @*<div class="form-group">
            <label asp-for="PeriodeEvenement"></label>
            <input asp-for="PeriodeEvenement" class="form-control" />
            <span class="text-danger" asp-validation-for="PeriodeEvenement"></span>
        </div>*@
        <div>
            <strong>Are you sure you want to delete '@Model.Title'?</strong>
        </div>

        <button class="btn btn-danger" type="submit">Delete</button>
    </form>

dotNet Core Groepsopdracht/Views/Event/Detail.cshtml
@model EventDetailViewModel
@{
    ViewData["Title"] = "Detail";
    List<EventPeriodViewModel> periods = new List<EventPeriodViewModel>();

    periods = Model.Periods;

}

<h2 style="background: #343A40;color:white; padding:10px;">@Model.Title</h2>

<div class="container">
    <div class="d-flex flex-row ">

        <div class="p-1 justify-content-start">
            @*desc*@
            <h3>Beschrijving</h3>
            <p>@Model.Description</p>
        </div>

        @*picture*@
        <div class="p-3 justify-content-end">
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <img class="image" src="@Model.Image" />
            }
        </div>
    </div>

    @*cap*@
    <h3>Capaciteit</h3>
    @if (Model.MinCap == 0 && Model.MaxCap != 0)
    {
        <p>Dit event heeft geen minimum reservaries maar wel een maximum van @Model.MaxCap reservaties.</p>
    }
    else if (Model.MinCap != 0 && Model.MaxCap == 0)
    {
        <p>Dit event heeft geen maximum reservaries maar wel een minimum van @Model.MinCap reservaties.</p>
    }
    else if (Model.MinCap == 0 && Model.MaxCap == 0)
    {
        <p>Dit event heeft geen maximum en minimum reservaties</p>
    }
    else
    {
        <p>Dit event start met een capaciteit van minimum @Model.MinCap en maximum @Model.MaxCap reservaties.</p>
    }

    <h3>Adres</h3>
    <p>@Model.Street @Model.Number, @Model.ZipCode @Model.City</p>

    @*price*@
    <h3>Prijs per ticket</h3>
    @{
        double prijs = 0;
    }
    @if (Double.TryParse(Model.Price, out prijs))//checkt if price een double is
    {
        @if (prijs <= 0)
        {
            <p>Gratis</p>
        }
        else
        {
            <p>&euro;@Model.Price</p>
        }
    }
    else//if Price = "ertyuiojhjhgftuyi" > auto naar gratis = cheat but okay
    {
        <p>Gratis</p>
    }


    @*picture*@
    <h3>Data</h3>
    @*<div class="card-deck row" style="margin-bottom: 5px">*@
    <div class="row" style="margin-bottom: 5px">

        @for (int i = 0; i < periods.Count; i++)
        {
            int a = i + 1;
            <div class="card col-lg-4" style="margin:5px">
                @* <h5 class="card-header">Dag @a</h5>*@
                <div class="card-body">
                    @*<h5 class="card-title">@periods[i].Start.DayOfWeek @periods[i].Start.ToShortDateString()</h5>*@
                    <h5 class="card-title">@periods[i].Start.ToString("D", System.Globalization.CultureInfo.CreateSpecificCulture("nl-BE"))</h5>
                    @if (periods[i].Start == periods[i].End)
                    {
                        <p class="card-text">Start om @String.Format("{0: HH:mm}", periods[i].Start)</p>
                    }
                    else
                    {
                        <p class="card-text">Van @String.Format("{0: HH:mm}", periods[i].Start) tot @String.Format("{0: HH:mm}", periods[i].End)</p>
                    }

                </div>
            </div>
        }

    </div>

    @* TODO: check if btn works after implementing reservations *@
    <br />
    <a class="btn-primary p-1 m-1" asp-area="" asp-controller="Reservation" asp-action="Create" asp-route-Id="@Model.Id">
        Reserveer
    </a>
    <a class="btn-primary p-1 m-1" asp-area="" asp-controller="Event" asp-action="Index">
        Terug
    </a>
</div>
<br />
@if (Model.Sponsors != null)
{
    <h3>Sponsors</h3>
    if (Model.Sponsors.Count() == 0)
    {
        <p>Er zijn nog geen sponsors voor dit event.</p>
    }
    else
    {
        foreach (var x in Model.Sponsors)
        {
            <img class="img" src="@x.Photo" />

        }
    }
}

<style>
    .card-title:first-letter {
        text-transform: capitalize;
    }

    .img {
        height: 100px;
        width: 100px;
        margin: 20px;
        margin-top: 100px;
    }
</style>

dotNet Core Groepsopdracht/Views/Event/PeriodEditViewModel.cshtml
@model EventEditViewModel
@Html.EditorFor(model => model.PeriodLijst)

dotNet Core Groepsopdracht/Views/Event/PeriodeViewModel.cshtml
@model EventCreateViewModel
@Html.EditorFor(model => model.PeriodLijst)