dotNet Core Groepsopdracht/Controllers/NewsController.cs
using dotNet_Core_Groepsopdracht.Areas.Identity.Data;
using dotNet_Core_Groepsopdracht.Attributes;
using dotNet_Core_Groepsopdracht.Data.Database;
using dotNet_Core_Groepsopdracht.Entities;
using dotNet_Core_Groepsopdracht.Models;
using dotNet_Core_Groepsopdracht.Services.Design;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace dotNet_Core_Groepsopdracht.Controllers {
	public class NewsController : Controller {
		private readonly IDatabase _database;
		private readonly UserManager<User> _userManager;
		private readonly IPhotoService _photoService;

		public NewsController(IDatabase database, UserManager<User> userManager, IPhotoService photoService) {
			_database = database;
			_userManager = userManager;
			_photoService = photoService;
		}

		public IActionResult Index( ) {
			List<NewsIndexViewModel> viewModelList = new List<NewsIndexViewModel>();

			foreach (NewsItem x in _database.GetNewsItems( )) {
				NewsIndexViewModel newModel = new NewsIndexViewModel {
					Title = x.Title,
					Content = x.Content,
					Id = x.Id,
					ImageUrl = x.ImageUrl
				};
				viewModelList.Add(newModel);
			}

			return View(viewModelList);
		}

		[HttpGet]
		[PermissionAuthorize(Permissions.CreateNewsItem, PermissionAuthorizeType.HasAny)]
		public IActionResult Create( ) {
			NewsCreateViewModel newsitem = new NewsCreateViewModel();
			return View(newsitem);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[PermissionAuthorize(Permissions.CreateNewsItem, PermissionAuthorizeType.HasAny)]
		public IActionResult Create([FromForm] NewsCreateViewModel viewModel) {
			if (TryValidateModel(viewModel)) {
				string imageUrl = null;
				if (viewModel.Image != null) imageUrl = _photoService.UploadedFile(viewModel.Image);
				NewsItem newsItem = new NewsItem()
				{
					Id = Guid.NewGuid(),
					Content = viewModel.Content,
					Title = viewModel.Title,
					Author = _userManager.GetUserAsync(User).Result,
					DateCreated = DateTime.Now,
					Reactions = new List<Reaction>(),
					ImageUrl = imageUrl
				};

				_database.AddNewsItem(newsItem);
				return RedirectToAction(nameof(Index));
			} else {
				return View(viewModel);
			}
		}



		[HttpGet]
		public IActionResult Edit(Guid id) {
			NewsItem newsitemToEdit = _database.FindNewsItemById(id);
			if (newsitemToEdit == null) return new NotFoundResult( );

			User user = _userManager.GetUserAsync(User).Result;

			if (user is null) {

				return RedirectToAction(nameof(Detail), new { id });
			}
			user = _database.FindUserById(user.Id);
			//check if news is yours or not if it aint do you have permission to edit others newsarticle?
			if (newsitemToEdit.AuthorId != user.Id || user.HasPerm(Permissions.EditNewsItem)) //if NOT your NewsArticle
			{

				NewsEditViewModel newsEditViewModel = new NewsEditViewModel()
					{
					Id = newsitemToEdit.Id,
					Title = newsitemToEdit.Title,
					Content = newsitemToEdit.Content,
					ImageUrl = newsitemToEdit.ImageUrl
				};
				return View(newsEditViewModel);
			} else {
				return RedirectToAction(nameof(Detail), new { id });
			}
		}

		[HttpPost]
		public IActionResult Edit(Guid id, [FromForm] NewsEditViewModel newsEditViewModel) {
			if (!TryValidateModel(newsEditViewModel)) return View(newsEditViewModel);
			NewsItem newsitemToEdit = _database.FindNewsItemById(id);
			newsitemToEdit.Title = newsEditViewModel.Title;
			newsitemToEdit.DateAdjusted = DateTime.Now;
			newsitemToEdit.Content = newsEditViewModel.Content;
			if (newsEditViewModel.Image != null) newsitemToEdit.ImageUrl = _photoService.UploadedFile(newsEditViewModel.Image);
			// Id, DateCreated, Author (User) and Reactions cannot be changed
			_database.UpdateNewsItem(newsitemToEdit, id);
			return RedirectToAction(nameof(Detail), new { id });
		}

		[HttpGet]
		public IActionResult Detail(Guid id) {
			NewsItem newsItem = _database.FindNewsItemById(id);
			List<NewsDetailReactionViewModel> reactions = newsItem.Reactions
				.OrderByDescending(x => x.DateMade)
				.Select(x => new NewsDetailReactionViewModel {
					Id = x.Id,
					Title = x.Title,
					DateMade = x.DateMade,
					AuthorId = x.Author.Id,
					AuthorUserName = x.Author.UserName,
					Content = x.Content
				}).ToList( );

			return View(new NewsDetailViewModel {
				Id = id,
				Title = newsItem.Title,
				AuthorId = newsItem.Author.Id,
				DateCreated = newsItem.DateCreated,
				DateAdjusted = newsItem.DateAdjusted,
				Content = newsItem.Content,
				ImageUrl = newsItem.ImageUrl,
				AuthorUserName = newsItem.Author.UserName,
				Reactions = reactions
			});
		}

		[HttpPost]
		public IActionResult Detail(Guid id, NewsDetailViewModel viewModel) {
			NewsItem newsItem = _database.FindNewsItemById(id);
			if (!TryValidateModel(viewModel)) {
				List<NewsDetailReactionViewModel> reactions = newsItem.Reactions.Select(x => new NewsDetailReactionViewModel {
					Title = x.Title,
					DateMade = x.DateMade,
					AuthorId = x.Author.Id,
					AuthorUserName = x.Author.UserName,
					Content = x.Content
				}).ToList( );
				return View(new NewsDetailViewModel {
					Title = newsItem.Title,
					AuthorId = newsItem.Author.Id,
					DateCreated = newsItem.DateCreated,
					DateAdjusted = newsItem.DateAdjusted,
					Content = newsItem.Content,
					ImageUrl = newsItem.ImageUrl,
					AuthorUserName = newsItem.Author.UserName,
					Reactions = reactions,
					ReactionTitle = viewModel.ReactionTitle,
					Reaction = viewModel.Reaction
				});
			}
			Reaction reaction = new Reaction(){
				Id = Guid.NewGuid(),
				Title = viewModel.ReactionTitle,
				DateMade = DateTime.Now,
				Author = _userManager.GetUserAsync(User).Result,
				Content = viewModel.Reaction,
				NewsItem = _database.FindNewsItemById(id)
			};
			_database.AddReaction(reaction);
			//newsItem.Reactions.Add(reaction);
			//_database.UpdateNewsItem(newsItem, id);
			return RedirectToAction("Detail", new { id = id });

		}


		[HttpGet]
		public IActionResult Delete(Guid id) {
			NewsItem newsToDelete = _database.FindNewsItemById(id);
			if (newsToDelete == null) return new NotFoundResult( );

			NewsDeleteViewModel newsDeleteViewModel = new NewsDeleteViewModel(){
				Id = newsToDelete.Id,
				Title = newsToDelete.Title,
				DateCreated = newsToDelete.DateCreated,
				Content = newsToDelete.Content,
				AuthorUserName = newsToDelete.Author.UserName,
			};
			return View(newsDeleteViewModel);
		}

		[HttpPost]
		public IActionResult ConfirmDelete(Guid id) {
			NewsItem newsToDelete = _database.FindNewsItemById(id);
			if (newsToDelete == null) return new NotFoundResult( );

			_database.RemoveNewsItem(newsToDelete);


			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult DeleteReaction(Guid id) {
			Reaction reactionToDelete = _database.FindReactionById(id);
			if (reactionToDelete == null) return new NotFoundResult( );
			NewsItem sourceNewsItem = _database.FindNewsItemById(reactionToDelete.NewsItemId);
			_database.RemoveReaction(reactionToDelete);
			return RedirectToAction("Detail", new { id = sourceNewsItem.Id });
		}
	}
}

dotNet Core Groepsopdracht/Views/News/Create.cshtml
@model NewsCreateViewModel


<h2> Artikel aanmaken</h2>
<form asp-controller="News" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" class="form-control" style="height: 300px"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"> Foto :</label>
        <input asp-for="Image" class="form-control" />
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <button class="btn btn-primary" type="submit">Artikel aanmaken</button>
    <button class="btn btn-warning" type="reset">Reset</button>
</form>

dotNet Core Groepsopdracht/Views/News/Delete.cshtml
@model NewsDeleteViewModel
<form asp-controller="News" asp-action="ConfirmDelete" asp-route-id="@Model.Id" method="post">

    <h5 class="mb-5">Bent u zeker dat u het newsitem '@Model.Title' wilt verwijderen?</h5>

    <div class="form-group">
        <label asp-for="AuthorUserName"></label>
        <input asp-for="AuthorUserName" class="form-control" readonly="readonly" />
        <span class="text-danger" asp-validation-for="AuthorUserName"></span>
    </div>
    <div class="form-group">
        <label asp-for="DateCreated"></label>
        <input asp-for="DateCreated" class="form-control" readonly="readonly" />
        <span class="text-danger" asp-validation-for="DateCreated"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Content"></label>
        <input asp-for="Content" class="form-control" readonly="readonly" />
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>


    <a class="btn btn-primary mr-5" asp-controller="News" asp-action="Index">Terug naar overzicht</a>
    <button class="btn btn-danger mr-5" type="submit">Verwijder NewsItem</button>
</form>

dotNet Core Groepsopdracht/Views/News/Detail.cshtml
@model NewsDetailViewModel
@{ ViewData["Title"] = Model.Title;}
@using dotNet_Core_Groepsopdracht.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject dotNet_Core_Groepsopdracht.Data.Database.IDatabase _database
@inject UserManager<User> _userManager;
@{
    User user = _userManager.GetUserAsync(User).Result;
    if (user != null) user = _database.FindUserById(_userManager.GetUserAsync(User).Result.UserId);
}

<div>
    @*TODO: Add author info*@

    <h2>@Model.Title</h2>

    @*TODO: make dates small and well positiond*@
    <p>
        Aangemaakt op: @Model.DateCreated.ToString("dd/MM/yyyy") door @Model.AuthorUserName.
        @if (!(Model.DateAdjusted is null))
        {
            DateTime dateAdjusted = (DateTime)Model.DateAdjusted;
            <text>Laatst aangepast op: @dateAdjusted.ToString("dd/MM/yyyy"). </text>
        }
    </p>
    @if (!string.IsNullOrEmpty(Model.ImageUrl))
    {
        <img class="image" src="@Model.ImageUrl" />
    }
    <br /><br />
    <p>@Html.Raw(Model.Content)</p>

    @if (Model.Reactions.Count > 0)
    {
        <h3 class="mt-5 mb-4">Reacties</h3>
        <div id="reactions-container">

            @foreach (NewsDetailReactionViewModel reaction in Model.Reactions)
            {
                <div class="pt-4 pl-4 pr-4" style="border:1px solid lightgrey;">
                    <p>
                        <span style="font-weight:bolder">@reaction.Title</span><br />
                        <span style="font-size:smaller">Door @reaction.AuthorUserName op @reaction.DateMade</span>
                    </p>
                    <p>@reaction.Content</p>

                    @if (user != null && user.HasPerm(dotNet_Core_Groepsopdracht.Entities.Permissions.DeleteReaction))
                    {
                        <p>
                            <a class="btn btn-danger " asp-area="" asp-controller="News" asp-action="DeleteReaction" asp-route-Id="@reaction.Id">Verwijder</a>
                        </p>
                    }
                </div>
            }
        </div>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <form asp-action="Detail" method="post" asp-route-id="@Model.Id">
            <h4 class="mt-5 mb-4">Voeg een reactie toe</h4>
            <div class="form-group">
                <label asp-for="ReactionTitle"></label>
                <input asp-for="ReactionTitle" class="form-control" />
                <span class="text-danger" asp-validation-for="ReactionTitle"></span>
            </div>

            <div class="form-group">
                <label asp-for="Reaction"></label>
                <textarea rows="5" asp-for="Reaction" class="form-control"></textarea>
                <span class="text-danger" asp-validation-for="Reaction"></span>
            </div>
            <button class="btn btn-primary" type="submit">Plaats reactie</button>
        </form>

    }

    <br />
    <br />
    <a class="btn btn-primary mr-5" asp-area="" asp-controller="News" asp-action="Index" asp-route-Id="@Model.Id">Terug</a>

    @if (user != null && User.Identity.IsAuthenticated && (user.HasPerm(dotNet_Core_Groepsopdracht.Entities.Permissions.EditNewsItem) || user.Id == Model.AuthorId))
    {
        <a class="btn btn-primary mr-5" asp-area="" asp-controller="News" asp-action="Edit" asp-route-Id="@Model.Id">Aanpassen</a>
        <a class="btn btn-danger mr-5" asp-area="" asp-controller="News" asp-action="Delete" asp-route-Id="@Model.Id">Verwijderen</a>
    }
</div>

dotNet Core Groepsopdracht/Views/News/Edit.cshtml
@model NewsEditViewModel


<form asp-controller="News" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea rows="5" asp-for="Content" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    @*TODO: How to display bool and provide option to change status??*@
    @*Create extra string property to display Approved or Not-approved*@
    <div class="form-group">
        <p>
            @if (Model.ImageUrl != null)
            {
                <img src="@Model.ImageUrl" />
            }
        </p>
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" />
            <span class="text-danger" asp-validation-for="Image"></span>
</div>
    <input type="hidden" asp-for="ImageUrl" />
    <button class="btn btn-primary" type="submit">Bewaren</button>
    <button class="btn btn-warning" type="reset">Reset</button>
</form>

@*//TODO: Author / user? Cannot be changed => Display author?
    //TODO: link with reactions? Reactions cannot be edited ...
    
    *@

dotNet Core Groepsopdracht/Views/News/Index.cshtml
@model IEnumerable<NewsIndexViewModel>
@using dotNet_Core_Groepsopdracht.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject dotNet_Core_Groepsopdracht.Data.Database.IDatabase _database
@inject UserManager<User> _userManager;

@{ViewData["Title"] = "Nieuws"; }
<h1>Nieuws</h1>
@{ User user = _userManager.GetUserAsync(User).Result;
    if (user != null) { user = _database.FindUserById(user.Id); }
}
@if (user != null && User.Identity.IsAuthenticated && user.HasPerm(dotNet_Core_Groepsopdracht.Entities.Permissions.CreateNewsItem))
{
    <a class="btn btn-primary mt-3 mb-3" asp-controller="News" asp-action="Create">Artikel aanmaken</a>
}
<style>
    #newsarticle {
        height: 200px;
        background-size: cover;
        color: white;
        font-size: 20px;
        position: relative;
        margin: 5px;
        text-shadow: 1px 1px #000000;
    }

    @@media (min-width: 768px) {
        #newsarticle {
            height: 350px;
            background-size: cover;
            color: white;
            font-size: 25px;
            position: relative;
            margin: 5px;
            text-shadow: 1px 1px #000000;
        }
    }

    #newsarticle span {
        position: absolute;
        bottom: 10px;
        left: 10px;
    }
</style>

@if (Model != null && Model.Any())
{
    <div class="row container">
        @foreach (var nieuws in Model)
        {
            <div class="col-lg-6 col-sm-12">
                <a asp-controller="News" asp-action="Detail" asp-route-id="@nieuws.Id">
                    <div style="margin-bottom:30px; background-image: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 40%), url('@nieuws.ImageUrl');"
                         id="newsarticle" class="rounded"><span>@nieuws.Title</span></div>
                    </a>
                </div>
            }
    </div>
}

else
{
    <h3>Er zijn geen nieuwsartikels</h3>
}